# this uses https://github.com/mjoldfield/Arduino-Makefile
 
ARDUINO_DIR        = /Applications/Arduino.app/Contents/Resources/Java
ARDMK_DIR          = ${HOME}/bin/Arduino-Makefile
ARDUINO_SKETCHBOOK = ${HOME}/Documents/Arduino
 
BOARD_TAG          = uno
ARDUINO_PORT       = /dev/cu.usb*
ARDUINO_LIBS       = 
 
include ${ARDMK_DIR}/arduino-mk/Arduino.mk